[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pricing"
version = "0.1.0"
description = "Stochastic Volatility Option Pricing Project"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "seaborn",       
    "statsmodels",   
    "jupyterlab",  
]

[project.optional-dependencies]
dev = [
    "pytest",        
    "black",         
    "isort",         
]